import styles from "./layout.module.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css" />
        <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/css/bootstrap.min.css" />

        <script src="https://cdn.staticfile.org/popper.js/2.9.3/umd/popper.min.js"></script>

        <script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/js/bootstrap.min.js"></script>

      </head>

      <body className={styles.body}>
        <main className={styles.main}>
          {children}
        </main>
      </body>
    </html>
  )
}
