// import { Inter } from "next/font/google";
// import "./globals.css";
import styles from "./layout.module.css"
import Link from "next/link";
import { Menu } from "./menu";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">

      <head>
        <link rel="stylesheet" href="https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css" />
        <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/css/bootstrap.min.css" />

        <script src="https://cdn.staticfile.org/popper.js/2.9.3/umd/popper.min.js"></script>

        <script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/js/bootstrap.min.js"></script>

      </head>

      <body className={styles.body}>
        <main className={styles.main}>
          <div>
            <nav className={styles.nav}>
              <div className={styles.logo}>
                <Link href="/">
                  ReTradeHub
                </Link>
              </div>
              <div className={styles.plus} title="上传新的商品信息">
                <Link href="/product/register">
                  <i className={"fa fa-plus-circle fa-fw"} style={{ fontSize: "48px" }}></i>
                </Link>
              </div>
              <Menu />
            </nav>
          </div>

          <div>
            {children}
          </div>

          <div>
            <footer className={styles.footer}>
              <p>
                毕业设计名称：基于SpringBoot框架的社区旧货交易平台的设计与实现
              </p>
              <p>
                韩宇杰 20计科师范一班 2020114230
              </p>
            </footer>
          </div>
        </main>
      </body>
    </html>
  );
}
